from sqlalchemy import Integer, BigInteger, String, Float, Text, PrimaryKeyConstraint, ForeignKeyConstraint
# from models.occurrence import Occurrence
from sqlalchemy.orm import Mapped, mapped_column, relationship
from typing import Optional
from database import Base

class DnaDerived(Base):
   __tablename__ = 'dna_derived'

   data_source: Mapped[str] = mapped_column(String(4), primary_key=True)
   source_id: Mapped[str] = mapped_column(String(50), primary_key=True)

   occurrence_source_id: Mapped[Optional[str]] = mapped_column(String(50), index=True)
   
   datasetkey: Mapped[Optional[str]] = mapped_column(String(36))
   sampname: Mapped[Optional[str]] = mapped_column(Text)
   occurrenceID: Mapped[Optional[str]] = mapped_column(Text)
   projectname: Mapped[Optional[str]] = mapped_column(Text)
   experimentalfactor: Mapped[Optional[str]] = mapped_column(Text)
   samptaxonid: Mapped[Optional[str]] = mapped_column(Text)
   negconttype: Mapped[Optional[str]] = mapped_column(Text)
   posconttype: Mapped[Optional[str]] = mapped_column(Text)
   envbroadscale: Mapped[Optional[str]] = mapped_column(Text)
   envlocalscale: Mapped[Optional[str]] = mapped_column(Text)
   envmedium: Mapped[Optional[str]] = mapped_column(Text)
   subspecfgenlin: Mapped[Optional[str]] = mapped_column(Text)
   ploidy: Mapped[Optional[str]] = mapped_column(String(32))
   numreplicons: Mapped[Optional[str]] = mapped_column(Text)
   extrachromelements: Mapped[Optional[str]] = mapped_column(Text)
   estimatedsize: Mapped[Optional[float]] = mapped_column(Float)
   refbiomaterial: Mapped[Optional[str]] = mapped_column(Text)
   sourcematid: Mapped[Optional[str]] = mapped_column(Text)
   pathogenicity: Mapped[Optional[str]] = mapped_column(String(100))
   bioticrelationship: Mapped[Optional[str]] = mapped_column(Text)
   specifichost: Mapped[Optional[str]] = mapped_column(Text)
   hostspecrange: Mapped[Optional[str]] = mapped_column(Text)
   hostdiseasestat: Mapped[Optional[str]] = mapped_column(Text)
   trophiclevel: Mapped[Optional[str]] = mapped_column(String(64))
   propagation: Mapped[Optional[str]] = mapped_column(Text)
   encodedtraits: Mapped[Optional[str]] = mapped_column(Text)
   reltooxygen: Mapped[Optional[str]] = mapped_column(String(64))
   isolgrowthcondt: Mapped[Optional[str]] = mapped_column(Text)
   sampcollecdevice: Mapped[Optional[str]] = mapped_column(Text)
   sampcollecmethod: Mapped[Optional[str]] = mapped_column(Text)
   sampmatprocess: Mapped[Optional[str]] = mapped_column(Text)
   sizefrac: Mapped[Optional[str]] = mapped_column(Text)
   sampsize: Mapped[Optional[str]] = mapped_column(Text)
   sampvolwednaext: Mapped[Optional[str]] = mapped_column(Text)
   sourceuvig: Mapped[Optional[str]] = mapped_column(Text)
   virusenrichappr: Mapped[Optional[str]] = mapped_column(Text)
   nuclacidext: Mapped[Optional[str]] = mapped_column(Text)
   nuclacidamp: Mapped[Optional[str]] = mapped_column(Text)
   libsize: Mapped[Optional[int]] = mapped_column(Integer)
   libreadsseqd: Mapped[Optional[int]] = mapped_column(BigInteger)
   liblayout: Mapped[Optional[str]] = mapped_column(String(32))
   libvector: Mapped[Optional[str]] = mapped_column(Text)
   libscreen: Mapped[Optional[str]] = mapped_column(Text)
   targetgene: Mapped[Optional[str]] = mapped_column(String(100))
   targetsubfragment: Mapped[Optional[str]] = mapped_column(String(100))
   pcrprimers: Mapped[Optional[str]] = mapped_column(Text)
   mid: Mapped[Optional[str]] = mapped_column(Text)
   adapters: Mapped[Optional[str]] = mapped_column(Text)
   pcrcond: Mapped[Optional[str]] = mapped_column(Text)
   seqmeth: Mapped[Optional[str]] = mapped_column(String(100))
   seqqualitycheck: Mapped[Optional[str]] = mapped_column(Text)
   chimeracheck: Mapped[Optional[str]] = mapped_column(Text)
   taxident: Mapped[Optional[str]] = mapped_column(Text)
   assemblyqual: Mapped[Optional[str]] = mapped_column(Text)
   assemblyname: Mapped[Optional[str]] = mapped_column(Text)
   assemblysoftware: Mapped[Optional[str]] = mapped_column(Text)
   annot: Mapped[Optional[str]] = mapped_column(Text)
   numbercontig: Mapped[Optional[int]] = mapped_column(Integer)
   featpred: Mapped[Optional[str]] = mapped_column(Text)
   refdb: Mapped[Optional[str]] = mapped_column(Text)
   simsearchmeth: Mapped[Optional[str]] = mapped_column(Text)
   taxclass: Mapped[Optional[str]] = mapped_column(Text)
   recover_16s: Mapped[Optional[str]] = mapped_column("16srecover", Text) # needed to rename column in python because can't start with number
   recover_16s_software: Mapped[Optional[str]] = mapped_column("16srecoversoftware", Text) # needed to rename column in python because can't start with number
   trnas: Mapped[Optional[int]] = mapped_column(Integer)
   trnaextsoftware: Mapped[Optional[str]] = mapped_column(Text)
   complscore: Mapped[Optional[float]] = mapped_column(Float)
   complsoftware: Mapped[Optional[str]] = mapped_column(Text)
   complappr: Mapped[Optional[str]] = mapped_column(Text)
   contamscore: Mapped[Optional[float]] = mapped_column(Float)
   contamscreeninput: Mapped[Optional[str]] = mapped_column(Text)
   contamscreenparam: Mapped[Optional[str]] = mapped_column(Text)
   decontamsoftware: Mapped[Optional[str]] = mapped_column(Text)
   sorttech: Mapped[Optional[str]] = mapped_column(Text)
   singlecelllysisappr: Mapped[Optional[str]] = mapped_column(Text)
   singlecelllysisprot: Mapped[Optional[str]] = mapped_column(Text)
   wgaampappr: Mapped[Optional[str]] = mapped_column(Text)
   wgaampkit: Mapped[Optional[str]] = mapped_column(Text)
   binparam: Mapped[Optional[str]] = mapped_column(Text)
   binsoftware: Mapped[Optional[str]] = mapped_column(Text)
   reassemblybin: Mapped[Optional[str]] = mapped_column(Text)
   magcovsoftware: Mapped[Optional[str]] = mapped_column(Text)
   viridentsoftware: Mapped[Optional[str]] = mapped_column(Text)
   predgenometype: Mapped[Optional[str]] = mapped_column(Text)
   predgenomestruc: Mapped[Optional[str]] = mapped_column(Text)
   detectype: Mapped[Optional[str]] = mapped_column(Text)
   otuclassappr: Mapped[Optional[str]] = mapped_column(Text)
   otuseqcompappr: Mapped[Optional[str]] = mapped_column(Text)
   otudb: Mapped[Optional[str]] = mapped_column(Text)
   hostpredappr: Mapped[Optional[str]] = mapped_column(Text)
   hostpredestacc: Mapped[Optional[str]] = mapped_column(Text)
   url: Mapped[Optional[str]] = mapped_column(Text)
   sop: Mapped[Optional[str]] = mapped_column(Text)
   pcrprimerforward: Mapped[Optional[str]] = mapped_column(Text)
   pcrprimerreverse: Mapped[Optional[str]] = mapped_column(Text)
   pcrprimernameforward: Mapped[Optional[str]] = mapped_column(Text)
   pcrprimernamereverse: Mapped[Optional[str]] = mapped_column(Text)
   pcrprimerreference: Mapped[Optional[str]] = mapped_column(Text)
   dnasequence: Mapped[Optional[str]] = mapped_column(Text)
   concentration: Mapped[Optional[float]] = mapped_column(Float)
   concentrationunit: Mapped[Optional[str]] = mapped_column(String(32))
   methoddeterminationconcentrationandratios: Mapped[Optional[str]] = mapped_column(Text)
   ratioofabsorbance260230: Mapped[Optional[float]] = mapped_column(Float)
   ratioofabsorbance260280: Mapped[Optional[float]] = mapped_column(Float)
   annealingtemp: Mapped[Optional[float]] = mapped_column(Float)
   annealingtempunit: Mapped[Optional[str]] = mapped_column(String(16))
   probereporter: Mapped[Optional[str]] = mapped_column(Text)
   probequencher: Mapped[Optional[str]] = mapped_column(Text)
   ampliconsize: Mapped[Optional[str]] = mapped_column(Text)
   thresholdquantificationcycle: Mapped[Optional[float]] = mapped_column(Float)
   baselinevalue: Mapped[Optional[str]] = mapped_column(Text)
   quantificationcycle: Mapped[Optional[float]] = mapped_column(Float)
   automaticthresholdquantificationcycle: Mapped[Optional[str]] = mapped_column(Text)
   automaticbaselinevalue: Mapped[Optional[str]] = mapped_column(Text)
   contaminationassessment: Mapped[Optional[str]] = mapped_column(Text)
   partitionvolume: Mapped[Optional[str]] = mapped_column(Text)
   partitionvolumeunit: Mapped[Optional[str]] = mapped_column(Text)
   estimatednumberofcopies: Mapped[Optional[str]] = mapped_column(Text)
   amplificationreactionvolume: Mapped[Optional[str]] = mapped_column(Text)
   amplificationreactionvolumeunit: Mapped[Optional[str]] = mapped_column(Text)
   pcranalysissoftware: Mapped[Optional[str]] = mapped_column(Text)
   experimentalvariance: Mapped[Optional[str]] = mapped_column(Text)
   pcrprimerlod: Mapped[Optional[str]] = mapped_column(Text)
   pcrprimerloq: Mapped[Optional[str]] = mapped_column(Text)
   _event_id: Mapped[Optional[str]] = mapped_column(Text)
   id: Mapped[Optional[str]] = mapped_column(Text, comment="From OBIS, not sure what this is, may be the universal OccurrenceID from DarwinCore")
   _id: Mapped[Optional[str]] = mapped_column(Text)
   _event_id: Mapped[Optional[str]] = mapped_column(Text)
   level: Mapped[Optional[int]] = mapped_column(Integer)

   __table_args__ = (
      PrimaryKeyConstraint('data_source', 'source_id', name='dna_derived_pkey'),
      ForeignKeyConstraint(
         ['data_source', 'occurrence_source_id'],
         ['occurrence.data_source', 'occurrence.source_id'],
         name='fk_dna_occurrrence'
      ),
      )
   
   # Add relationship so we can do things like DnaDerived.occurrence for querying
   occurrence = relationship("Occurrence", foreign_keys=[data_source, occurrence_source_id])